name: Build all tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests-vanilla:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kuleuven-micas/gemmini-test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build all baremetal tests
        run: |
          autoconf
          mkdir -p build
          cd build
          ../configure
          make -j BAREMETAL_ONLY=1
      - name: Run all tests
        run: |
          cd build
          make -j test-baremetal-bareMetalC

  tests-mlir:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kuleuven-micas/gemmini-test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build all baremetal MLIR tests
        run: |
          autoconf
          mkdir -p build
          cd build
          ../configure
          make -j BAREMETAL_ONLY=1 MLIR=1
      - name: Run all tests
        run: |
          cd build
          make -j test-baremetal-bareMetalC MLIR=1
